name: Flutter CI
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

env:
  flutter_version: "3.13.0"
jobs:

  Setup-Flutter:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Restore packages
        run: flutter pub get
      - name: Analyze
        run: flutter analyze --no-congratulate
      - name: Run tests
        run: flutter test --coverage
    # - name: Upload coverage to codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
