name: Publish to pub.dev

on:
  create:
    tags:
    - 'v*'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Display version
        run: echo "Publish version ${{ env.RELEASE_VERSION }}"
      - uses: dart-lang/setup-dart@v1
      - name: Setup yq
        uses: shiipou/setup-yq-action@v2.0.2
      - name: Set version
        uses: mikefarah/yq@master
        with:
          cmd: 'yq -i ".version=\"${{ env.RELEASE_VERSION }}\"" pubspec.yaml'
      - name: Install dependencies
        run: dart pub get
      - name: Publish
        run: dart pub publish --force