name: Release
on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha
      - "*.x"

env:
  flutter_version: "3.3.9"

jobs:
  get-next-version:
    uses: lenra-io/github-actions/.github/workflows/get-version.yml@main
    
  release:
    needs: [get-next-version]
    if: ${{ needs.get-next-version.outputs.will-release == 'true' }}
    uses: lenra-io/github-actions/.github/workflows/release.yml@main
  publish:
    name: publish
    needs: [get-next-version, release]
    if: ${{ needs.get-next-version.outputs.will-release == 'true' }}
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.get-next-version.outputs.version }}
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Set version
        uses: mikefarah/yq@master
        with:
          cmd: 'yq -i ".version=\"${{ env.VERSION }}\"" pubspec.yaml'
      - name: Install dependencies
        run: dart pub get
      - name: Publish
        run: dart pub publish --force
